pp_root_dir: "/work/scratch-pw2/vs480/pp_files"

stashes:
  - "34001"  # O3
  - "34002"  # NO
  - "34996"  # NO2
  - "34003"  # NO3
  - "34005"  # N2O5
  - "34006"  # HO2NO2
  - "34007"  # HONO2 (HNO3)
  - "34049"  # N2O
  - "50062"  # airmass
  - "50063"  # tropmask

dataset_suites:
  e1-st1-hc: u-br438
  e1-st2-hc: u-dh394
  e2-st2-hc: u-dq680
  e2-st2+lnox4-hc: u-ds004
  e2-st2+adv8A-hc: u-dq721
  e2-st2+adv8B-hc: u-dq731